/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Credits = {
  _id: string;
  _type: "credits";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  pageTitle?: string;
  pageDescription?: string;
  imageCredits?: Array<{
    imageName?: string;
    source?: "unsplash" | "pexels" | "pixabay" | "freepik" | "other";
    authorName?: string;
    authorUrl?: string;
    imageUrl?: string;
    license?: string;
    usedOn?: string;
    _type: "imageCredit";
    _key: string;
  }>;
  otherCredits?: Array<{
    resourceName?: string;
    authorName?: string;
    authorUrl?: string;
    resourceUrl?: string;
    license?: string;
    usedOn?: string;
    _type: "otherCredit";
    _key: string;
  }>;
  footerNote?: string;
};

export type LegalNotices = {
  _id: string;
  _type: "legalNotices";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteInfo?: {
    siteUrl?: string;
    siteDescription?: string;
  };
  organizationInfo?: {
    organizationName?: string;
    legalForm?: string;
    capital?: string;
    registrationNumber?: string;
    registrationOffice?: string;
    address?: {
      street?: string;
      city?: string;
      country?: string;
    };
    contactPhone?: string;
  };
  publicationDirector?: {
    name?: string;
    position?: string;
  };
  hostingInfo?: {
    providerName?: string;
    providerAddress?: {
      street?: string;
      city?: string;
      country?: string;
    };
    providerPhone?: string;
    providerWebsite?: string;
  };
  disclaimers?: {
    contentDisclaimer?: string;
    copyrightNotice?: string;
    liabilityDisclaimer?: string;
  };
};

export type LegalMatters = {
  _id: string;
  _type: "legalMatters";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  associationInfo?: {
    associationName?: string;
    legalRepresentative?: string;
    address?: {
      street?: string;
      city?: string;
      country?: string;
    };
    contactEmail?: string;
    contactPhone?: string;
  };
  technicalInfo?: {
    hostingProvider?: string;
    lastUpdated?: string;
  };
  dataProtectionAuthority?: {
    authorityName?: string;
    authorityWebsite?: string;
  };
  legalReferences?: {
    rgpdReference?: string;
    togoleseLawReference?: string;
  };
};

export type WebsiteSections = {
  _id: string;
  _type: "websiteSections";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroSection?: {
    pretitle?: string;
    title?: string;
    text?: string;
    buttonData?: {
      url?: string;
      text?: string;
    };
  };
  projectSection?: {
    pretitle?: string;
    text?: string;
  };
  projectsPageSection?: {
    pretitle?: string;
    title?: string;
    text?: string;
  };
  missionSection?: {
    pretitle?: string;
    text?: string;
  };
  teamSection?: {
    pretitle?: string;
    title?: string;
    text?: string;
  };
  contactSection?: {
    title?: string;
    text?: string;
  };
  contactInfo?: {
    address?: string;
    schedules?: string;
    phone?: string;
    email?: string;
  };
};

export type ElsTogoSettings = {
  _id: string;
  _type: "elsTogoSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  footer?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  ogImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    metadataBase?: string;
    _type: "image";
  };
};

export type MissionCard = {
  _id: string;
  _type: "missionCard";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  text?: string;
  iconImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  order?: number;
};

export type Member = {
  _id: string;
  _type: "member";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  firstname?: string;
  name?: string;
  role?: string;
  bio?: string;
  memberImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  email?: string;
  phone?: string;
  socialLinks?: {
    linkedin?: string;
    twitter?: string;
    github?: string;
    website?: string;
  };
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  id?: string;
  title?: string;
  accroche?: string;
  description?: string;
  goal?: string;
  howWeDo?: string;
  results?: string;
  date?: string;
  place?: string;
  category?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "category";
  };
  projectImg?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  slug?: Slug;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  color?: string;
};

export type SanityAssistInstructionTask = {
  _type: "sanity.assist.instructionTask";
  path?: string;
  instructionKey?: string;
  started?: string;
  updated?: string;
  info?: string;
};

export type SanityAssistTaskStatus = {
  _type: "sanity.assist.task.status";
  tasks?: Array<{
    _key: string;
  } & SanityAssistInstructionTask>;
};

export type SanityAssistSchemaTypeAnnotations = {
  _type: "sanity.assist.schemaType.annotations";
  title?: string;
  fields?: Array<{
    _key: string;
  } & SanityAssistSchemaTypeField>;
};

export type SanityAssistOutputType = {
  _type: "sanity.assist.output.type";
  type?: string;
};

export type SanityAssistOutputField = {
  _type: "sanity.assist.output.field";
  path?: string;
};

export type SanityAssistInstructionContext = {
  _type: "sanity.assist.instruction.context";
  reference?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "assist.instruction.context";
  };
};

export type AssistInstructionContext = {
  _id: string;
  _type: "assist.instruction.context";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  context?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type SanityAssistInstructionUserInput = {
  _type: "sanity.assist.instruction.userInput";
  message?: string;
  description?: string;
};

export type SanityAssistInstructionPrompt = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  } | ({
    _key: string;
  } & SanityAssistInstructionFieldRef) | ({
    _key: string;
  } & SanityAssistInstructionContext) | ({
    _key: string;
  } & SanityAssistInstructionUserInput)>;
  style?: "normal";
  listItem?: never;
  markDefs?: null;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type SanityAssistInstructionFieldRef = {
  _type: "sanity.assist.instruction.fieldRef";
  path?: string;
};

export type SanityAssistInstruction = {
  _type: "sanity.assist.instruction";
  prompt?: SanityAssistInstructionPrompt;
  icon?: string;
  title?: string;
  userId?: string;
  createdById?: string;
  output?: Array<({
    _key: string;
  } & SanityAssistOutputField) | ({
    _key: string;
  } & SanityAssistOutputType)>;
};

export type SanityAssistSchemaTypeField = {
  _type: "sanity.assist.schemaType.field";
  path?: string;
  instructions?: Array<{
    _key: string;
  } & SanityAssistInstruction>;
};
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./sanity/lib/queries.ts
// Variable: settingsQuery
// Query: *[_type == "elsTogoSettings"][0] {  _id,  title,  description,  footer,  ogImage {    asset->{      _id,      url,      metadata {        dimensions {          width,          height        }      }    },    alt,    metadataBase  }}
export type SettingsQueryResult = {
  _id: string;
  title: string | null;
  description: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  footer: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  ogImage: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        dimensions: {
          width: number | null;
          height: number | null;
        } | null;
      } | null;
    } | null;
    alt: string | null;
    metadataBase: string | null;
  } | null;
} | null;
// Variable: projectsQuery
// Query: *[_type == "project"] | order(_createdAt desc) {  _id,  id,  title,  accroche,  description,  goal,  howWeDo,  results,  date,  place,  category->{    _id,    title,    description,    color  },  projectImg,  "slug": slug.current}
export type ProjectsQueryResult = Array<{
  _id: string;
  id: string | null;
  title: string | null;
  accroche: string | null;
  description: string | null;
  goal: string | null;
  howWeDo: string | null;
  results: string | null;
  date: string | null;
  place: string | null;
  category: {
    _id: string;
    title: string | null;
    description: string | null;
    color: string | null;
  } | null;
  projectImg: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  slug: string | null;
}>;
// Variable: membersQuery
// Query: *[_type == "member"] | order(_createdAt desc) {  _id,  firstname,  name,  role,  bio,  memberImage,  email,  phone,  socialLinks}
export type MembersQueryResult = Array<{
  _id: string;
  firstname: string | null;
  name: string | null;
  role: string | null;
  bio: string | null;
  memberImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  email: string | null;
  phone: string | null;
  socialLinks: {
    linkedin?: string;
    twitter?: string;
    github?: string;
    website?: string;
  } | null;
}>;
// Variable: categoriesQuery
// Query: *[_type == "category"] | order(title asc) {  _id,  title,  description,  color}
export type CategoriesQueryResult = Array<{
  _id: string;
  title: string | null;
  description: string | null;
  color: string | null;
}>;
// Variable: missionCardsQuery
// Query: *[_type == "missionCard"] | order(order asc, title asc) {  _id,  title,  text,  iconImage,  order}
export type MissionCardsQueryResult = Array<{
  _id: string;
  title: string | null;
  text: string | null;
  iconImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  order: number | null;
}>;
// Variable: websiteSectionsQuery
// Query: *[_type == "websiteSections"] | order(_updatedAt desc)[0] {  _id,  heroSection,  projectSection,  projectsPageSection,  missionSection,  teamSection,  contactSection,  contactInfo}
export type WebsiteSectionsQueryResult = {
  _id: string;
  heroSection: {
    pretitle?: string;
    title?: string;
    text?: string;
    buttonData?: {
      url?: string;
      text?: string;
    };
  } | null;
  projectSection: {
    pretitle?: string;
    text?: string;
  } | null;
  projectsPageSection: {
    pretitle?: string;
    title?: string;
    text?: string;
  } | null;
  missionSection: {
    pretitle?: string;
    text?: string;
  } | null;
  teamSection: {
    pretitle?: string;
    title?: string;
    text?: string;
  } | null;
  contactSection: {
    title?: string;
    text?: string;
  } | null;
  contactInfo: {
    address?: string;
    schedules?: string;
    phone?: string;
    email?: string;
  } | null;
} | null;
// Variable: legalMattersQuery
// Query: *[_type == "legalMatters"] | order(_updatedAt desc)[0] {  _id,  associationInfo,  technicalInfo,  dataProtectionAuthority,  legalReferences}
export type LegalMattersQueryResult = {
  _id: string;
  associationInfo: {
    associationName?: string;
    legalRepresentative?: string;
    address?: {
      street?: string;
      city?: string;
      country?: string;
    };
    contactEmail?: string;
    contactPhone?: string;
  } | null;
  technicalInfo: {
    hostingProvider?: string;
    lastUpdated?: string;
  } | null;
  dataProtectionAuthority: {
    authorityName?: string;
    authorityWebsite?: string;
  } | null;
  legalReferences: {
    rgpdReference?: string;
    togoleseLawReference?: string;
  } | null;
} | null;
// Variable: creditsQuery
// Query: *[_type == "credits"] | order(_updatedAt desc)[0] {  _id,  pageTitle,  pageDescription,  imageCredits,  otherCredits,  footerNote}
export type CreditsQueryResult = {
  _id: string;
  pageTitle: string | null;
  pageDescription: string | null;
  imageCredits: Array<{
    imageName?: string;
    source?: "freepik" | "other" | "pexels" | "pixabay" | "unsplash";
    authorName?: string;
    authorUrl?: string;
    imageUrl?: string;
    license?: string;
    usedOn?: string;
    _type: "imageCredit";
    _key: string;
  }> | null;
  otherCredits: Array<{
    resourceName?: string;
    authorName?: string;
    authorUrl?: string;
    resourceUrl?: string;
    license?: string;
    usedOn?: string;
    _type: "otherCredit";
    _key: string;
  }> | null;
  footerNote: string | null;
} | null;
